---
- name: Deploy Web Application
  hosts: my_servers
  become: true
  tasks:
    - name: Copy requirements
      copy:
        src: './requirements.txt'
        dest: '/project/'

    - name: Copy app
      copy:
        src: './app.py'
        dest: '/project/'

    - name: Install Python
      apt:
        name: python3
        state: present

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install venv
      apt:
        name: python3-venv
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Manually create the initial virtualenv
      command:
        cmd: python3 -m venv venv

    - name: Install Node.js and npm
      apt:
        name: 
        - nodejs
        - npm
        state: present

    - name: Install virtualenv
      command:
        cmd: python3 -m pip install virtualenv

    - name: Install Python dependencies
      pip:
        requirements: /project/requirements.txt
        virtualenv: /project/venv

    - name: Install Python requirements
      command:
        cmd: python3 -m pip install -r requirements.txt

    - name: Copy Frontend files
      copy:
        src: './frontend/build'
        dest: '/project/frontend/build'

    - name: Copy nginx.conf
      copy:
        src: ./frontend/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - Reload Nginx

    - name: Start Nginx service
      service:
        name: nginx
        state: restarted

    - name: Start server
      command:
        cmd: python3 -m uvicorn app:app
        chdir: /project

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
